import { identifierName } from '@angular/compiler';

export const dataFile: any = [
  {
    id: 1,
    description: 'Beyond Earth',
    imgUrl: '/assets/thumbnails/beyond-earth/trending/large.jpg',
    imgSUrl: '/assets/thumbnails/beyond-earth/trending/small.jpg',
    deskUrl: '/assets/thumbnails/beyond-earth/regular/large.jpg',
    tabUrl: '/assets/thumbnails/beyond-earth/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/beyond-earth/regular/small.jpg',
    year: 2019,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },

  {
    id: 2,
    description: 'Bottom Gear',
    imgUrl: '/assets/thumbnails/bottom-gear/trending/large.jpg',
    imgSUrl: '/assets/thumbnails/bottom-gear/trending/small.jpg',
    deskUrl: '/assets/thumbnails/bottom-gear/regular/large.jpg',
    tabUrl: '/assets/thumbnails/bottom-gear/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/bottom-gear/regular/small.jpg',
    year: 2021,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },

  {
    id: 3,
    description: 'Undiscovered Cities',
    imgUrl: '/assets/thumbnails/undiscovered-cities/trending/large.jpg',
    imgSUrl: '/assets/thumbnails/undiscovered-cities/trending/small.jpg',
    deskUrl: '/assets/thumbnails/undiscovered-cities/regular/large.jpg',
    tabUrl: '/assets/thumbnails/undiscovered-cities/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/undiscovered-cities/regular/small.jpg',
    year: 2019,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'E',
  },

  {
    id: 4,
    description: '1998',
    imgUrl: '/assets/thumbnails/1998/trending/large.jpg',
    imgSUrl: '/assets/thumbnails/1998/trending/small.jpg',
    deskUrl: '/assets/thumbnails/1998/regular/large.jpg',
    tabUrl: '/assets/thumbnails/1998/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/1998/regular/small.jpg',
    year: 2021,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: '18+',
  },

  {
    id: 5,
    description: 'Dark Side Of The Moon',
    imgUrl: '/assets/thumbnails/dark-side-of-the-moon/trending/large.jpg',
    imgSUrl: '/assets/thumbnails/dark-side-of-the-moon/trending/small.jpg',
    deskUrl: '/assets/thumbnails/dark-side-of-the-moon/regular/large.jpg',
    tabUrl: '/assets/thumbnails/dark-side-of-the-moon/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/dark-side-of-the-moon/regular/small.jpg',
    year: 2018,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 6,
    description: 'The Great Lands',
    imgUrl: '/assets/thumbnails/the-great-lands/regular/large.jpg',
    imgSUrl: '/assets/thumbnails/the-great-lands/trending/small.jpg',
    deskUrl: '/assets/thumbnails/the-great-lands/regular/large.jpg',
    tabUrl: '/assets/thumbnails/the-great-lands/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/the-great-lands/regular/small.jpg',
    year: 2019,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },

  {
    id: 7,
    description: 'The Diary',
    imgUrl: '/assets/thumbnails/the-diary/regular/large.jpg',
    imgSUrl: '/assets/thumbnails/the-diary/trending/small.jpg',
    deskUrl: '/assets/thumbnails/the-diary/regular/large.jpg',
    tabUrl: '/assets/thumbnails/the-diary/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/the-diary/regular/small.jpg',
    year: 2019,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 8,
    description: "Earth's Untouched",
    imgUrl: '/assets/thumbnails/earths-untouched/regular/large.jpg',
    imgSUrl: '/assets/thumbnails/earths-untouched/trending/small.jpg',
    deskUrl: '/assets/thumbnails/earths-untouched/regular/large.jpg',
    tabUrl: '/assets/thumbnails/earths-untouched/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/earths-untouched/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: '18+',
  },

  {
    id: 9,
    description: 'No Land Beyond',
    imgUrl: '/assets/thumbnails/no-land-beyond/regular/large.jpg',
    imgSUrl: '/assets/thumbnails/no-land-beyond/trending/small.jpg',
    deskUrl: '/assets/thumbnails/no-land-beyond/regular/large.jpg',
    tabUrl: '/assets/thumbnails/no-land-beyond/regular/medium.jpg',
    mobUrl: '/assets/thumbnails/no-land-beyond/regular/small.jpg',
    year: 2019,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'E',
  },

  {
    id: 10,
    description: 'During The Hunt',
    imgUrl: '/assets/thumbnails/during-the-hunt/regular/large.jpg',
    tabUrl: '/assets/thumbnails/during-the-hunt/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/during-the-hunt/regular/small.jpg',
    year: 2016,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 11,
    description: 'AutoSport The Series',
    imgUrl: '/assets/thumbnails/autosport-the-series/regular/large.jpg',
    tabUrl: '/assets/thumbnails/autosport-the-series/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/autosport-the-series/regular/small.jpg',
    year: 2016,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 12,
    description: 'Same Answer II',
    imgUrl: '/assets/thumbnails/same-answer-2/regular/large.jpg',
    tabUrl: '/assets/thumbnails/same-answer-2/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/same-answer-2/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'E',
  },

  {
    id: 13,
    description: 'Below Echo',
    imgUrl: '/assets/thumbnails/below-echo/regular/large.jpg',
    tabUrl: '/assets/thumbnails/below-echo/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/below-echo/regular/small.jpg',
    year: 2016,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 14,
    description: 'The Rockies',
    imgUrl: '/assets/thumbnails/the-rockies/regular/large.jpg',
    tabUrl: '/assets/thumbnails/the-rockies/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/the-rockies/regular/small.jpg',
    year: 2015,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'E',
  },

  {
    id: 15,
    description: 'Relentless',
    imgUrl: '/assets/thumbnails/relentless/regular/large.jpg',
    tabUrl: '/assets/thumbnails/relentless/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/relentless/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },

  {
    id: 16,
    description: 'Community of Ours',
    imgUrl: '/assets/thumbnails/community-of-ours/regular/large.jpg',
    tabUrl: '/assets/thumbnails/community-of-ours/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/community-of-ours/regular/small.jpg',
    year: 2018,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: '18+',
  },

  {
    id: 17,
    description: 'Van Life',
    imgUrl: '/assets/thumbnails/van-life/regular/large.jpg',
    tabUrl: '/assets/thumbnails/van-life/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/van-life/regular/small.jpg',
    year: 2015,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },

  {
    id: 18,
    description: 'The Heiress',
    imgUrl: '/assets/thumbnails/the-heiress/regular/large.jpg',
    tabUrl: '/assets/thumbnails/the-heiress/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/the-heiress/regular/small.jpg',
    year: 2021,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },

  {
    id: 19,
    description: 'Off the Track',
    imgUrl: '/assets/thumbnails/off-the-track/regular/large.jpg',
    tabUrl: '/assets/thumbnails/off-the-track/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/off-the-track/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: '18+',
  },

  {
    id: 20,
    description: 'Whispering Hill',
    imgUrl: '/assets/thumbnails/whispering-hill/regular/large.jpg',
    tabUrl: '/assets/thumbnails/whispering-hill/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/whispering-hill/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'E',
  },

  {
    id: 21,
    description: '112',
    imgUrl: '/assets/thumbnails/112/regular/large.jpg',
    tabUrl: '/assets/thumbnails/112/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/112/regular/small.jpg',
    year: 2013,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 22,
    description: 'Lone Heart',
    imgUrl: '/assets/thumbnails/lone-heart/regular/large.jpg',
    tabUrl: '/assets/thumbnails/lone-heart/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/lone-heart/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'E',
  },

  {
    id: 23,
    description: 'Production Line',
    imgUrl: '/assets/thumbnails/production-line/regular/large.jpg',
    tabUrl: '/assets/thumbnails/production-line/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/production-line/regular/small.jpg',
    year: 2018,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 24,
    description: 'Dogs',
    imgUrl: '/assets/thumbnails/dogs/regular/large.jpg',
    tabUrl: '/assets/thumbnails/dogs/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/dogs/regular/small.jpg',
    year: 2016,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'E',
  },

  {
    id: 25,
    description: 'Asia in 24 Days',
    imgUrl: '/assets/thumbnails/asia-in-24-days/regular/large.jpg',
    tabUrl: '/assets/thumbnails/asia-in-24-days/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/asia-in-24-days/regular/small.jpg',
    year: 2020,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 26,
    description: 'The Tasty Tour',
    imgUrl: '/assets/thumbnails/the-tasty-tour/regular/large.jpg',
    tabUrl: '/assets/thumbnails/the tasty-tour/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/the-tasty-tour/regular/small.jpg',
    year: 2016,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: 'PG',
  },

  {
    id: 27,
    description: 'Darker',
    imgUrl: '/assets/thumbnails/darker/regular/large.jpg',
    tabUrl: '/assets/thumbnails/darker/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/darker/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: '18+',
  },

  {
    id: 28,
    description: 'Unresolved Cases',
    imgUrl: '/assets/thumbnails/unresolved-cases/regular/large.jpg',
    tabUrl: '/assets/thumbnails/unresolved-cases/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/unresolved-cases/regular/small.jpg',
    year: 2018,
    category: 'TV Series',
    icon: '/assets/icon-category-tv.svg',
    rated: '18+',
  },

  {
    id: 29,
    description: 'Mission: Satan',
    imgUrl: '/assets/thumbnails/mission-saturn/regular/large.jpg',
    tabUrl: '/assets/thumbnails/mission-saturn/regular/medium.jpg',
    mobUrl:'/assets/thumbnails/mission-saturn/regular/small.jpg',
    year: 2017,
    category: 'Movie',
    icon: '/assets/icon-category-movie.svg',
    rated: 'PG',
  },
];

export const bookmarkData = {
  BookmarkEmpty: '/assets/emptyBookmark.png',
  BookmarkFull: '/assets/fullBookmark.png',
};

export const playButton = {
  playIcon: '/assets/playButton.png',
};
